### ISSUE TITLE
PSF Project

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/WLShear#2]
We are engaged in a project to explore how PSF measurement errors propagate into LSST results.

There are several sub-parts to this project, which we will collate under this epic.

Summary of plan as presented in the [PSF telecon](https://docs.google.com/document/d/1ZGsgGu9MWlz_E3dZTNmhFx_osStl9zz1Qs0kO8XgqT8/edit): 

**Part 1**

- [ ] Generate multiple realisations of star fields (simulated from updated [ImSim](https://github.com/LSSTDESC/imSim) or PhoSim and run them through the DM stack [PSFEx](https://github.com/astromatic/psfex). [Check with [SSim](https://github.com/LSSTDESC/SSim_DC1) to see if they are already planning this.]
- [ ] Find the mean PSF error from these realisations.
- [ ] Explore alternative PSF measurement strategies from [Piff](https://github.com/rmjarvis/Piff) to see if they reduce this.

**Part 2**
- [ ]  **(a)** (Temporary) Rescale HSC mean residual shears/PSF values to LSST scales to generate a residual template. or using simple toy models, e.g., purely radial PSF anisotropy patterns, purely horizontal (in focal plane coordinates), etc. These are way oversimplified but might give some insight on the importance of various aspects of the dither patterns. **(b)** (When part one has results) Take the mean PSF error from part one. Generate [dither patterns](https://github.com/LSST-nonproject/sims_maf_contrib/blob/master/tutorials/Dithers.ipynb) using MAF/[OpSim](https://github.com/lsst/sims_operations).
- [ ]  Explore how these average down and the impact on final shear measurements and spectra: **(a)** see how the rho statistics and PSF model fractional size residual averages  down with time, and **(b)** put together the framework for how that propagates into shear statistics (using [analytical Gaussian formalism](https://arxiv.org/pdf/1507.05603.pdf) rather than simulations).
- [ ]  Explore how changing the survey strategy affects how this averaging down varies with time

**Goals**

- Ascertain how current state-of-the-art PSF modeling software failure modes propagate into WL two-point correlation functions
    * Consider per-exposure PSF model failure modes
    * Estimate how they propagate into systematic errors in `coaddPSF` given the survey strategy
- Use results to:
    * Provide feedback to DM on PSF modeling performance
    * Develop templates for systematic errors that can be marginalized over in a WL analysis
- Since PSF modeling routines are an active development area for DM, framework must be reusable as our understanding of per-exposure PSF modeling errors evolves

See [slides](https://docs.google.com/presentation/d/1urWLh4qvY0PTXdTwFHnhW6mZtHghINURocmxuFEdC1o/edit?pli=1#slide=id.g2512e74f57_0_12) for more info.
